files:
  - 
    source: /msg/angular.json
    translation: '/msg/%file_name%_%locale%.%file_extension%'
    languages_mapping:
      locale:
        de: de
        zh-CN: zh
        en-GB: en
        et: et
        fr: fr
